### ISSUE TITLE
How to improve the frame rate and run sample code with errors in ffmpeg decoding

### ISSUE THREAD

**Issue by Zz928** [hansalemaos/adbblitz#2]
1.The highest frame rate now is 35. How can I improve the frame rate？
2.Errors occurred during ffmpeg decoding and cv2. imshow displays a blurred screen

Error message：

error while decoding MB 14 41, bytestream -6
missing picture in access unit with size 15216
No start code is found.
Error splitting the input into NAL units.
error while decoding MB 12 39, bytestream -14
missing picture in access unit with size 18960
No start code is found.
Error splitting the input into NAL units.
error while decoding MB 4 30, bytestream -24
missing picture in access unit with size 58592
No start code is found.
Error splitting the input into NAL units.
error while decoding MB 24 34, bytestream -38
missing picture in access unit with size 28880
No start code is found.
Error splitting the input into NAL units.
error while decoding MB 4 31, bytestream -14
missing picture in access unit with size 36944
No start code is found.
Error splitting the input into NAL units.

**Comment by hansalemaos** [comment]
What device are you using? 35 is actually not bad at all, but it still can be improved. With ADB (screencap), you never go over 20. When do the errors happen? At the beginning or every once in a while?

**Comment by Zz928** [comment]
I used oneplus 7t 
If the image content is complex, errors will occur.
For example, games and videos.


> 你用的是什么设备？35其实一点都不差，但还是可以提高的。有了ADB (screencap)，你永远不会超过20。错误发生在什么时候？开始的时候还是每隔一段时间？

**Comment by hansalemaos** [comment]
That makes sense, because de encoder has a lot to do and less resources to encode the vídeo.
